"Updated git shortcuts and fzf for Linux"

diff --git a/dotfiles/my_settings_zsh b/dotfiles/my_settings_zsh
--- a/dotfiles/my_settings_zsh
+++ b/dotfiles/my_settings_zsh
@@ -45,7 +45,7 @@ alias tmuxkillall='tmux kill-server'
 export TERM="xterm-256color"
 export HISTCONTROL="ignoredups:erasedups"
 
-[ -d "${HOME}/.settings" ] && cd "${HOME}/.settings" && git pull && cd -
+# [ -d "${HOME}/.settings" ] && cd "${HOME}/.settings" && git pull && cd -
 
 export MYSETTINGSDIR="${HOME}/.config/my_settings"
 [ ! -d "${MYSETTINGSDIR}" ] && mkdir -p "${MYSETTINGSDIR}"
@@ -353,29 +353,79 @@ alias gpg-check='gpg2 --keyserver-options auto-key-retrieve --verify'
 alias gpg-retrieve='gpg2 --keyserver-options auto-key-retrieve --receive-keys'
 alias battery_stat='upower -i "$( upower -e | grep BAT )"'
 
+check_git() {
+  GIT_STAT="$(git rev-parse --is-inside-work-tree 2> /dev/null)"
+  if [[ "${GIT_STAT}" != *"true"* ]]; then
+    printf 'Current directory is not a git repo.\n'
+    return 1
+  fi
+
+  if [ ! -x "$(command -v git)" ]; then
+    printf 'git not found in PATH\n'
+    return 1
+  fi
+
+  if [ ! -z "$1" ]; then
+    if [ ! -x "$(command -v $1)" ]; then
+      printf '%s not found in PATH\n' "$1"
+      return 1
+    fi
+  fi
+
+  return 0
+}
+
 gitc() {
-    git commit -a -m "\"${1}\""
-    git push
+  check_git
+  if [[ "$?" == "1" ]]; then
+    return;
+  fi
+  git commit -a -m "\"${1}\"" && git push
 }
+
+# Cleaning up git repo from long time non-activity
 gcatchup() {
-    git fetch --all
-    git reset --hard origin/master
-    git pull
+  check_git
+  if [[ "$?" == "1" ]]; then
+    return;
+  fi
+  git fetch --all && git reset --hard origin/master && git pull
 }
+
+# Add tag to current repo
 gtag() {
-    git tag -a "\"${1}\""
+  check_git
+  if [[ "$?" == "1" ]]; then
+    return;
+  fi
+  git tag -a "\"${1}\""
 }
+
+# git - add files
 alias gaddup='git add -u'
 alias gaddall='git add .'
+
+# Log git activity for past 2 weeks or 8 h
 gitlog2w() {
-    for day in $(seq 14 -1 0); do
-        git log --before="${day} days" --after="$("$day"+1) days" --format=oneline | wc -l
-    done | spark
+  check_git spark
+  if [[ "$?" == "1" ]]; then
+    return;
+  fi
+
+  for day in $(seq 14 -1 0); do
+    git log --before="${day} days" --after="$(("$day"+1)) days" --format=oneline | wc -l
+  done | spark
 }
+
 gitlog8h() {
-    for hour in $(seq 8 -1 0); do
-        git log --before="${hour} hours" --after="$("$hour"+1) hours" --format=oneline | wc -l
-    done | spark
+  check_git spark
+  if [[ "$?" == "1" ]]; then
+    return;
+  fi
+
+  for hour in $(seq 8 -1 0); do
+    git log --before="${hour} hours" --after="$(("$hour"+1)) hours" --format=oneline | wc -l
+  done | spark
 }
 
 # [ ! -d "$HOME/.zsh" ] && mkdir -p "$HOME/.zsh"
