Updated Linux package manager shortcuts...
Now we can just call pkgup to update on the platforms using apt, dnf,
yum, and pacman.

If it works correctly on all my platforms, it will be implemented to
Fish shell as well.

diff --git a/dotfiles/my_settings_zsh b/dotfiles/my_settings_zsh
--- a/dotfiles/my_settings_zsh
+++ b/dotfiles/my_settings_zsh
@@ -207,18 +207,86 @@ alias rsync='rsync -azvh --info=progress2'
 alias sudo='sudo -H'
 alias free='free -m'
 
-if [ -x "$(command -v apt)" ] && [ -x "$(command -v apt-get)" ]; then
-	alias aptup='sudo apt-get -y update && sudo apt-get -y upgrade'
-	alias aptin='sudo apt-get -y update && sudo apt-get -y upgrade && sudo apt-get install'
-fi
-if [ -x "$(command -v dnf)" ]; then
-	alias dnfup='sudo dnf -y update'
-	alias dnfin='sudo dnf -y install'
-fi
-if [ -x "$(command -v pacman)" ] && [ -x "$(command -v pamac)" ] && [ -x "$(command -v pacman-mirrors)" ]; then
-	alias pmyy='sudo pacman-mirrors --continent && sudo pacman -Syyu && sudo pamac upgrade -a'
-	alias pmin='sudo pacman -Syyu'
-fi
+function aptup () {
+    if [ -x "$(command -v apt-get)" ]; then
+        sudo apt-get -y update && sudo apt-get -y upgrade
+    elif [ -x "$(command -v apt)" ]; then
+        sudo apt -y update && sudo apt -y upgrade
+    else
+        printf 'ERROR: Cannot find apt or apt-get in the system.\n'
+        exit 1
+    fi
+    exit 0
+}
+
+function aptin () {
+    aptup && sudo apt-get -y install "$@"
+}
+
+function dnfup () {
+    if [ -x "$(command -v dnf)" ]; then
+        sudo dnf -y update
+    else
+        printf 'ERROR: Cannot find dnf in the system!! Maybe try with Yum?\n'
+        exit 1
+    fi
+    exit 0
+}
+
+function dnfin () {
+    dnfup && sudo dnf -y install "$@"
+}
+
+function yumup () {
+    if [ -x "$(command -v yum)" ]; then
+        sudo yum -y update
+    else
+        printf 'ERROR: Cannot find yum!\n'
+        exit 1
+    fi
+    exit 0
+}
+
+function yumin () {
+    yumup && yum -y install "$@"
+}
+
+function pacmansync () {
+    if [ -x "$(command -v pacman)" ] && [ -x "$(command -v pamac)" ] && [ -x "$(pacman-mirrors)" ]; then
+        sudo pacman-mirrors --continent
+        sudo pacman -Syuu
+        sudo pamac upgrade -a
+    else
+        printf 'pacman system seems to be incomplete!\n'
+        return 1
+    fi
+    exit 0
+}
+
+function pacmanin () {
+    pacmansync && sudo pacman -Syuu "$@"
+}
+
+function pkgup () {
+    printf 'Updating the system with package manager!\n'
+    aptup 2>&1 && return 0
+    dnfup 2>&1 && return 0
+    yumup 2>&1 && return 0
+    pacmansync 2>&1 && return 0
+}
+
+# if [ -x "$(command -v apt)" ] && [ -x "$(command -v apt-get)" ]; then
+# 	alias aptup='sudo apt-get -y update && sudo apt-get -y upgrade'
+# 	alias aptin='sudo apt-get -y update && sudo apt-get -y upgrade && sudo apt-get install'
+# fi
+# if [ -x "$(command -v dnf)" ]; then
+# 	alias dnfup='sudo dnf -y update'
+# 	alias dnfin='sudo dnf -y install'
+# fi
+# if [ -x "$(command -v pacman)" ] && [ -x "$(command -v pamac)" ] && [ -x "$(command -v pacman-mirrors)" ]; then
+# 	alias pmyy='sudo pacman-mirrors --continent && sudo pacman -Syyu && sudo pamac upgrade -a'
+# 	alias pmin='sudo pacman -Syyu'
+# fi
 
 alias cd..='cd ..' # Just like MS-DOS
 alias ...='cd ../..'
